name: Build project pipeline
on:
  push:
jobs:
  build-sample_application:
    name: Build the project binary
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout proc repo
        uses: actions/checkout@v3.1.0
        with:
          submodules: true
      - name: Build proc binary
        uses: xanderhendriks/action-build-stm32cubeide@v12.0
        with:
          project-path: 'STM32Cube'
          project-target: 'processor_board/Debug'
